server:
  port: 8088
spring:
  application:
    name: h2-demo
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:h2demo;AUTO_RECONNECT=TRUE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2
      trace: false
      web-allow-others: true
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml