server:
  port: 8089
spring:
  application:
    name: h2-flowable
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:h2flowable;AUTO_RECONNECT=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      trace: false
      web-allow-others: true
  data:
    mongodb:
      uri: mongodb://youxuepai:youxuepai@localhost:27017
      database: task_data
flowable:
  common:
    app:
      security:
        type: idm
      role-prefix:
      idm-admin:
        user: admin
        password: test
  idm:
    ldap:
      enabled: false
    app:
      admin:
        user-id: admin
        password: test
  process:
    definition-cache-limit: 512
    async:
      executor:
        default-async-job-acquire-wait-time: PT5S
        default-timer-job-acquire-wait-time: PT5S
  task:
    app:
      rest-enabled: true
  admin:
    app:
      server-config:
        app:
          user-name: admin
          password: 123456

  form-field-validation-enabled: false
  experimental:
    debugger:
      enabled: true