server:
  port: 8089
spring:
  application:
    name: h2-flowable
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:h2flowable;AUTO_RECONNECT=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      trace: false
      web-allow-others: true
flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: 123456