spring:  
  application:
    name: microservice-res-graph
  cloud:
    nacos:
      discovery:
        server-addr: ${config.common.register.url}
        namespace: ${config.common.register.namespace}
########################## seata  #########################
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
  tx-service-group: ${spring.application.name}
  service:
    vgroup-mapping:
      microservice-res-graph: default
  config:
    type: nacos
    nacos:
      namespace: ${spring.cloud.nacos.config.namespace}
      serverAddr: ${spring.cloud.nacos.config.server-addr}
      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      dataId: seata-server.yaml
  #      username: nacos #生产环境使用,使用acm,但非空的username会去尝试登录，不停的打印错误日志
  #      password: nacos
  registry:
    type: nacos
    nacos:
      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      namespace: ${config.common.register.namespace}
      serverAddr: ${config.common.register.url}
      group: SEATA_GROUP
  client:
    tm:
      default-global-transaction-timeout: 1000000
########################## seata end #########################