server:
  port: 8089
data-one:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:data1;AUTO_RECONNECT=TRUE
    username: sa
    password:
data-two:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:data2;AUTO_RECONNECT=TRUE
    username: sa
    password:
spring:
  h2:
    console:
      enabled: true
      path: /h2
      trace: false
      web-allow-others: true